DROP TABLE IF EXISTS wishlists CASCADE;

CREATE TABLE wishlists (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  crypto_id VARCHAR(255) NOT NULL,
  img VARCHAR(255) NOT NULL,
  email_crypto_id VARCHAR(255) NOT NULL UNIQUE
);